/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.PantallasCCRS;

import com.PPAI.backend.backend.interfaces.IObservador;
import com.PPAI.backend.backend.models.MotivoFueraServicio;
import com.PPAI.backend.backend.models.MotivoTipo;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.util.List;

/**
 *
 * @author Miqueas
 */
public class Pantalla extends JFrame implements IObservador {

    private final JLabel lblMensaje = new JLabel();
    /**
     * Creates new form PantallaCCRS1
     */
    public Pantalla(Integer idPantalla) {
        initComponents();
        setTitle("Pantalla CCRS - ID: " + idPantalla);
        lblMensaje.setVisible(false);
        lblMensaje.setHorizontalAlignment(SwingConstants.CENTER); // centrar el texto

        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(lblMensaje, BorderLayout.CENTER);
    }
    
    public void mostrarEnPantalla(String mensaje) {
        lblMensaje.setVisible(true);
        lblMensaje.setText(mensaje);

    }

    @Override
    public void actualizar(int identificadorSismografo, String estado,  LocalDate fecha, String mensaje) {
        String mensajePantalla = "El sismografo Con ID: " + identificadorSismografo + "pasa al estado: " + estado;
        mostrarEnPantalla(mensajePantalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;

    // End of variables declaration//GEN-END:variables
}
