spring.mail.host=smtp.gmail.com
spring.mail.port=#Puerto que te ofrece gmail
spring.mail.username=# Tu gmail
spring.mail.password=#Password que te ofrece gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/basededatosppai?useSSL=false&serverTimezone=UTC
spring.datasource.username=miqueas
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
